language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t evaou/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true evaou/docker-react npm run test -- --coverage